### ISSUE TITLE
Should Api handle serialization too?

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#142]
It feels weird that deserialization is out of your control, but requests are just untyped `Vec<u8>`s.

Patches would be trickier to get right, though. Hmm..

**Comment by clux** [comment]
`Api::create` and `Api::replace` now expect typed objects that can be serialised to the specified `K`.

`Api::patch` (and proposed helpers around patch) requires extra work like what is proposed in #175 .

For the subresource `Api::replace_scale`.. kubernetes allows skipping out `Spec`, whereas `#[derive(CustomResource)]` does not (because it hardcodes .spec as set). Not sure what's sensible for that one; either we enforce `replace_scale` takes a full `K` (including a .spec that's ultimately unused by the api), or we enforce `replace_scale` only takes a `Scale` struct and we can nest it correctly..

**Comment by teozkr** [comment]
FWIW this applies to `replace_metadata` too. 

I like 2. Doesn't lead to a bunch of useless `unwrap()`s, doesn't cause confusion around whether other values are ignored, and avoids a bunch of useless clones.

**Comment by clux** [comment]
Going to close this upon further reflection.

- Don't really want to hamstring `kube-derive` for a special case like `replace_scale`.
- Api::patch with server-side apply is now standard.

Will document patch it a little better, then close.
