### ISSUE TITLE
example for updating conditions / status

### ISSUE THREAD

**Issue by debianmaster** [clux/kube-rs#154]
can you provide example for updating conditions / status on a CRD instance?

**Comment by clux** [comment]
conditions, i've advocated for using a struct with named conditions due to #43 
for manipulating the status object, i always found it best to patch in the fields you needed to change, as you need to change them.

here's an example that's part of a larger project, but you get might get the gist: https://github.com/babylonhealth/shipcat/blob/1e344ef398970f1ac34acc2ff0bf109c84c6f530/shipcat_cli/src/status.rs#L122-L151

better examples to come after #148
