### ISSUE TITLE
Remove implicit namespace handling?

### ISSUE THREAD

**Issue by teozkr** [clux/kube-rs#160]
Moving this into a separate issue since #150 got derailed (and partially resolved).

From that issue:

- write actions: can be inferred from object metadata
- read actions: should probably be taken explicitly instead

**Comment by teozkr** [comment]
Then again, I'm not sure how useful this is, since you can just share the `APIClient` instead.

**Comment by clux** [comment]
Yeah, I am not sure anymore now. Particular since the normal pattern (at least as far as I've written - which also mirrors the examples) is to either:

- do a bunch of actions on one type of resources in the same namespace (`Api::namespaced`)
- watch one particular resource in ALL namespaces (`Api::all`)

The current code setup favours that, and makes it less error prone (no 2 string arguments in a row, with less duplication).

However, when you have to other stuff like moving/copying one resource from one namespace to another (though have never had to do this myself outside of CI during migrations), then it is probably advantageous to not have the implicit namespace to not have it accidentally get shunted to the wrong namespace.

**Comment by teozkr** [comment]
Yeah.. the tricky bit is that in the standard controller scenario (watch X in all namespaces and manage Y accordingly), you want Y to be in the same ns as the X, not in some globally implicit ns.

**Comment by clux** [comment]
But then they are infrequently the same resource. X is the CRD in all namespaces, and Y the associated ones.

I guess the main thing we want is to prevent mistakes.

Maybe it makes sense to add `Api::get_namespaced` and only have the `_namespaced` functions be accessible if we did a `Api::all` to create them?

**Comment by clux** [comment]
Going to close this, as it's pretty stale and undefined atm. The only state in `Api` is now the `path_url` via the `Request`, and cloning it is cheap.

Think it's also sensible that an `Api` object is the mirror of a client-go client which has the following api:

```go
deploymentsClient := clientset.AppsV1().Deployments(apiv1.NamespaceDefault)
```

which also does implicit namespace handling.
