### ISSUE TITLE
Add support for core objects

### ISSUE THREAD

**Issue by awprice** [clux/kube-rs#2]
At the moment you can only list and watch non-core objects in the Kubernetes API - e.g. CRDs. Core object should be watchable too, e.g. Pods, Deployments, Ingresses etc.

Maybe we can expand ApiResource in https://github.com/clux/kube-rs/blob/master/src/api/resource.rs#L11 to have a `base` field which specifies the url base to use so core objects are supported?

**Comment by clux** [comment]
That might be a good solution, but it looks like the url can be constructed from those three parameters if we put more optionals in there. Or maybe just a raw enum of type -> url if that works. Most of the system looks generally consistent.

The current main issue is that it needs a different way of handling core objects, because they can have other fields than `.spec`. CRDs just go straight into `.spec` because it's the only thing right on the root object that is of value (and it's also user defined). Thus `Resource<T>` is: https://github.com/clux/kube-rs/blob/14a851d115ed8ea8ddeeb46398450d25862e3c11/src/api/resource.rs#L99-L107 and users discards most of the gunk in metadata as a consequence.

However [Deployment objects](https://docs.rs/k8s-openapi/0.4.0/k8s_openapi/api/apps/v1/struct.DeploymentSpec.html) likely want to grab `.status` as well, so we got to keep the metadata gunk on the `Reflector`.

Either we keep the gunk everywhere, or find the core cases perhaps. Have only noticed `.status` and `.spec` so far. Debating whether or not to just import some of the structs straight out of k8s-openapi and exposing them in a simpler way.

**Comment by clux** [comment]
NB: The following worked for `Deployments`:

```
      # make a reflector out of this:
        let deployresource = ApiResource {
            group: "apps".into(),
            resource: "deployments".into(),
            namespace: namespace.clone(),
        };
```

**Comment by awprice** [comment]
Sounds like adding more optionals is a good way to go. It would be awesome if you could get the k8s-openapi structs working! It would help me out alot.

**Comment by awprice** [comment]
Another feature that would help me out greatly would be the ability to watch objects in all namespaces.

**Comment by clux** [comment]
Watching in all namespaces should just be passing `namespace: None` in the future.

**Comment by clux** [comment]
Core object support explored in #3

**Comment by clux** [comment]
Initial idea available.

**Comment by awprice** [comment]
@clux Thanks mate! I'll give it a go.
