### ISSUE TITLE
Bring back `kube::Client::new`

### ISSUE THREAD

**Issue by rylev** [clux/kube-rs#203]
While `infer` is quite convenient, it is also fairly non-performant to have to fetch the configuration each time you need a client. For our project we get the config once and then pass it around as needed. It would be nice to be able to continue doing that.

**Comment by rylev** [comment]
I noticed there is a `From` impl for configuration. This is an extremely surprising API. While it might be convenient in certain situations, I would expect a `new` associated function.

**Comment by clux** [comment]
Appreciate that.

That whole setup is going to get a bit of a rework. The Config/Client boundry is super fuzzy and ill-defined atm because the Config actually creates the Client (which in itself is kind of surprising).

Plan on making `Configuration` actually configuration, and have `Client::new` do the instantiation of `reqwest::Client`.

**Comment by clux** [comment]
In the mean time you can do `Client::from(your_cached_config.clone())`, right?

**Comment by rylev** [comment]
That would be nice. I would indeed expect the configuration to not include `reqwest::Client`. And yes, the `From` impl allows me to work around this. 

I'm happy to help if you'd like me to take a stab at this.

**Comment by clux** [comment]
That would be great! If you'd like to take a stab at #205, then I'm happy to review.
