### ISSUE TITLE
default enable watch bookmarks

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#226]
Currently, you have to select whether to pass on `allowWatchBookmarks` to the api server via `ListParams`, but you always have to have a match arm for it in when you get a `WatchEvent` from `api.watch`.

We could simplify this by having bookmarks be a compile time feature that makes the struct larger if enabled, as well as it automatically being enabled in `ListParams::default`.

Is this a too small use of a feature?

**Comment by teozkr** [comment]
I would flip this and ask: where would you ever want to disable bookmarks? If you care about bandwidth: you'll want to implement them. If you don't care about bandwidth, it's a trivial match arm to add, and to me it feels perfectly "Rusty" to have to add friction to slower options (just like `Clone` vs `Copy`). If you run <1.16, the apiserver will just ignore the flag anyway. If you uncover some pathological case for bookmarks.. you'll probably want to disable them in the control plane instead of hunting down and patching every last client.

**Comment by teozkr** [comment]
Besides, there's the usual shpiel about cargo features causing breakage if they're not purely additive (since a sibling dependency might enable it for you, for example).

**Comment by clux** [comment]
Yeah, convinced by that argument. Thank you.

So flipping this, perhaps we should just enable them in `ListParams` by default instead because we, as a client, implement support for them now, and you have to handle them anyway.

**Comment by teozkr** [comment]
Sounds good to me.
