### ISSUE TITLE
#[derive(CustomResource)] path dependencies

### ISSUE THREAD

**Issue by semtexzv** [clux/kube-rs#227]
Current implementation of custom derive has a bunch or implicit assumptions about outer environment, which requires user to import crates under specific names.

I like to rename `serde_json` and `k8s_openapi` to `json` and `k8s` respectively, and It's impossible to do so currently
Changing the paths in the macro output to use undocumented re-exports from kube crate would solve this.

**Comment by clux** [comment]
Oh, interesting. You mean like having the macro generate code that depends on something like:

```rust
use kube_derive::serde_json::Deserialize;
```

Would that work? I don't want `kube_derive` to depend explicitly on `kube`, but that probably wasn't what you meant.

**Comment by semtexzv** [comment]
Yeah, could be. Goal is to reduce number of dependencies on external state in the custom derive.

**Comment by clux** [comment]
Revisiting this. Having dug into this more, turns out there's an open issue in rust-lang about this being hard: https://github.com/rust-lang/rust/issues/54363
Serde has a similar issue.

Practically, we would need some way to refer to the up to three runtime dependencies `kube-derive` has:

- `serde_json` (needed in both codegen and generated code)
- `schemars` (optional, only needed in runtime code, user needs to select feature flags)
- `k8s_openapi` (needed only in runtime code, user needs to select feature flags)

As per the PR, I don't want to re-export these from `kube`, because `kube-derive` is actually fine as a stand-alone crate (`schemars` is only needed there). Strangely, the dependency tree is actually more natural this way around (`kube` re-exports `kube-derive`).

If it was possible for `kube-derive` to re-export these three with non-default features by itself, and then have users progressively enhance them with their own feature selection (because we can only have one version of a given package), then I would be in favour of it.

Unfortunately, proc_macro crates do not support this:

```
error: `proc-macro` crate types currently cannot export any items other than functions tagged with `#[proc_macro]`, `#[proc_macro_derive]`, or `#[proc_macro_attribute]`
   --> /home/clux/repos/kube-rs/kube-derive/src/lib.rs:209:1
    |
209 | pub use serde_json;
    | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Thus, I am going to close this __for now__. Unless there's movement on this from the rust side, we are just going to list that you need to have these 2/3 crates available in scope - and not renamed - for `kube-derive` to work.
