### ISSUE TITLE
Listing pods cannot find pods that are currently terminating.

### ISSUE THREAD

**Issue by emilyaherbert** [clux/kube-rs#307]
Hello. I am writing an application that requires me to wait until pods have finished terminating, and I am planning to use a loop to pull a list of pods (by label) and exit once there are no pods remaining.

However, it seems that when listing pods, pods that are currently terminating do not show up. Is there some way to do this?

I am using `kube::api::typed::Api<kube::api::resource::Object<k8s_openapi::v1_17::api::core::v1::pod_spec::PodSpec, k8s_openapi::v1_17::api::core::v1::pod_status::PodStatus>>` `.list()` with a `ListParams` object.

(this issue is duplicated from here: https://github.com/Arnavion/k8s-openapi/issues/74)

**Comment by teozkr** [comment]
This is generally a bad idea to rely on, since there is no guarantee about how long a `Pod` will stay `Terminating`. Instead, you can either:

1. Add a finalizer, which will prevent the object from being deleted until you remove it again, or
2. Use [`.metadata.ownerReferences`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#ownerreference-v1-meta), or
3. Wait for the `Object`(s) to no longer exist (that is, `Api::get()` returns 404 or `Api::list()` no longer includes the object(s))

Which option is better depends on what you're trying to do. If you're trying to clean up after the pods themselves then 1 is the only reliable option. If you're deleting the pods as part of cleanup for some other resource then you should prefer 2. If you're just waiting for the objects to disappear as part of some process (like when waiting for `kubectl delete` to finish) then 3 should be fine.

> and I am planning to use a loop to pull a list of pods (by label) and exit once there are no pods remaining.

You probably want to use a [`kube_runtime::watcher`](https://docs.rs/kube-runtime/0.39.0/kube_runtime/watcher/fn.watcher.html) instead here (gets you immediate updates rather than waiting for the polling interval, less apiserver load, less traffic).

**Comment by clux** [comment]
You can do a watch on a pod directly like the `job_api` example if it's a short time watch (<5min). It does look like you're using an older version of kube if Api is generic over both Spec and Status btw.

But for your actual problem I think pods already in a `Terminating` state will not showing up in list by default. I think you need to either know those names and watch them, or use a field selector (in `ListParams`) to explicitly ask for Terminating phase pods.

**Comment by emilyaherbert** [comment]
I appreciate the detailed responses!

> But for your actual problem I think pods already in a `Terminating` state will not showing up in list by default. I think you need to either know those names and watch them, or use a field selector (in `ListParams`) to explicitly ask for Terminating phase pods.

This was the solution, I had to add a field selector to ensure that `list` found pods with `status.phase=Waiting` (i.e. Terminating).
