### ISSUE TITLE
port circleci to github actions

### ISSUE THREAD

**Issue by clux** [clux/kube-rs#562]
parallelisation issues and platform support issues on circleci is becoming ever more painful. some goals:

- [x] need better platform support for #508 (windos build working)
- [x] need more than parallelisation factor of 1 from circleci (they nerfed it quite hard) so we can run more tests (20 from github actions)
- [x] need better caching to speed up workflows (15min cycles are painful) - linked pr seems ok
- ~~maybe ditch musl (only used for integration test to shove into docker, do whatever is fastest)~~
- serve as an easy to understand example for users of kube #332

@kazk, I know you started on this in https://github.com/clux/kube-rs/blob/use-github-actions/.github/workflows/ci.yml from #510 (after discussion points in https://github.com/clux/kube-rs/issues/508#issuecomment-832205596). Am happy to resume that unless it ties in majorly with any potential `kube-test` plans in #382.

**Comment by kazk** [comment]
I experimented some more on my fork to avoid spamming everyone with failed tests. Maybe you can make use of it (https://github.com/kazk/kube-rs/tree/use-github-actions-2). I remember Windows build was painful because of OpenSSL. I had to install OpenSSL (https://github.com/kazk/kube-rs/commit/2ceed36992e4e0d6757cd49ab38124d2e60b4b8c), and couldn't figure out how to cache it, so it took a long time on each build. Tried vendored OpenSSL too (https://github.com/kazk/kube-rs/commit/b57f719165e7ae3d92f9b2043685e6998759cf16).

I think test steps can be simplified now because most tests can be covered at once by enabling all features. There are some tests for specific combinations of features, but that should be much less.

**Comment by clux** [comment]
Hah, I just confirmed the vendored vs manual install of openssl. 7 minutes to just install it...  The vendoring solution does seem to work well. Even with a musl build, so maybe that's just the solution.
