### ISSUE TITLE
list all objects once at init time

### ISSUE THREAD

**Issue by wonderflow** [clux/kube-rs#68]
Now informer just watch for new event, but If the controller crash and restart, events triggered between down time should have a chance to to resolved.

So I suggest add some function, so that we can list all the objects at initiate time.

**Comment by clux** [comment]
You need to track a resourceVersion to ask when to start getting events from. Too early is not always possible. Did you try https://docs.rs/kube/0.15.1/kube/api/struct.Informer.html#method.init_from ?.

**Comment by wonderflow** [comment]
In fact, I just want get the latest version once, but I didn't know the version when the informer is crashed or closed, so I can't use `init_from` with a version

**Comment by wonderflow** [comment]
In another world, I hope the informer can send me all the objects I watched once.

**Comment by wonderflow** [comment]
I hope to get something like this: 
```
fn list_resource(&self) -> Result<(Vec<WatchEvent<K>>, String)> {
        let req = self.resource.list(&self.params)?;
        let events = self.client.request_events::<Object<P,U>>(req)?;
        for e in events {
            self.events.write().unwrap().push_back(e);
        }
    }
```

**Comment by wonderflow** [comment]
@clux Do you have any suggestion?

**Comment by clux** [comment]
Hm, not sure I completely understand. You want `list_resource` to return all events "you watched once". I'm not sure what you mean by that. Also I don't know what your String return type is meant to be. The resourceVersion?

Maybe you need to track that in your app if you depend on not double handling resources.

Is there a standard way in go that you know this is supported?

**Comment by wonderflow** [comment]
I found out that it is  [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) who did this thing. Maybe we just need to add lister for informer.

**Comment by Ciantic** [comment]
Are you wondering about how to list the resources before starting to watch changes? E.g. here is [a List and then Watch implemented using client-go](https://www.martin-helmich.de/en/blog/kubernetes-crd-client.html):

> Most operators work by initially loading all relevant instances of a resource by using an initial List() call, and then subscribing to updates using a Watch() call.

I also agree that usecase could be shown in the watch example, it's not just about crashing, it's when you start the informer.

**Comment by wonderflow** [comment]
@Ciantic  Yes, I solve this issue by list of the resources myself before start informer. It could be better if the informer have this feature.

**Comment by clux** [comment]
This should work better in 0.22.0 now because `poll` is streaming and we update the version between every received event.

Thus, if there's an error, the next `.poll() will just continue from the last seen `resourceVersion`.
However, if we get a 410 Gone, we still reset the `resourceVersion` to latest; because there's nothing else we can do when we've gone out of history ([Bookmarks](https://kubernetes.io/docs/reference/using-api/api-concepts/#watch-bookmarks) #54 are meant to make this problem better in the future).

Current behavior: https://github.com/clux/kube-rs/blob/f71e7243ecdf4cd7513f03bb287eac1982c178cd/src/api/informer.rs#L174-L185 

If your controller / app outside kube-rs has a chance of crashing, then you need to save the `.version()` somewhere and feed that into `Informer::init_from` for your next reboot (and hope that you haven't gone out of history).

**Comment by wonderflow** [comment]
My initial advice was to give all the objects with the latest verison in the streaming when the informer was initialized. It doesn't matter with the revision of one object. But I think it could also be done by the controller / app outside rube-rs. So I think I could close this issue.

But I think the work you've done in 0.22.0 would still be very helpful!
Thanks again! @clux
