### ISSUE TITLE
replace reqwest ?

### ISSUE THREAD

**Issue by davidB** [clux/kube-rs#78]
Are you open to a PR to try to remove reqwest (very bloat in number of dependency) ?

I think with something like https://crates.io/crates/http_req + rust-tls.

**Comment by clux** [comment]
it's unlikely we want to change `reqwest` itself because that's a lot of functionality to replace, and we would need a lot better arguments than dependency bloat. Particularly since it's unlikely you'll escape the biggest dependencies like k8s-openapi and tokio anyway.

however, want to upgrade reqwest to support:

- rusttls feature #66 (with rusttls as a feature like everything else in the ecosystem)
- reqwest async release #63

**Comment by davidB** [comment]
I agree k8s-openapi is the longer to build, but tokio will be removed with reqwest, as lightweight http client doesn't use it.

**Comment by davidB** [comment]
Ok so wait for await/async stabilization
