### ISSUE TITLE
Calling Reflector::poll in separate thread/task

### ISSUE THREAD

**Issue by milesgranger** [clux/kube-rs#97]
Good day sir!

Regarding version 0.22.1

I'm trying to do as advised, calling `.poll()` in a separate task 

```rust
tokio::spawn(async move {
    loop {
        let _ = reflector.poll().await.unwrap();
    }
});
```
Results in:
```rust
tokio::spawn(async move {
    |     ^^^^^^^^^^^^ `dyn futures_core::stream::Stream<Item = std::result::Result<kube::api::resource::WatchEvent<kube::api::resource::Object<crd::gordo::gordo::GordoSpec, crd::gordo::gordo::GordoStatus>>, kube::Error>>` cannot be sent between threads safely
```

This will work however in 0.20.0

I've attempted wrapping the reflector, (naively) in `Arc<RwLock<Reflector<Gordo>>` to no avail. 

I really appreciate all your examples, but couldn't find any which actually put this into a different task, aside from `controller-rs` but that's on version 0.18 in which case this will work. 

When you have the time, could you give me a pointer?

**Comment by clux** [comment]
Ah what!? The `Stream` isn't `Send` :scream:

That's definitely a awkward. Kind of rushed out that release because all the examples work and delayed actix / threaded case because it's in a weird pre-2.0.0 state right now.

Definitely need to make some changes to make the threaded case work here ASAP. Thanks for the issue. Will start a branch and try things. Help from anyone else who are good at the type puzzle would also be appreciated :-) (cc @kitfre)

**Comment by clux** [comment]
Think we might need to change the internal client watch call to return a `BoxStream`, because the stream isn't even exposed to a `Reflector` and types still complain :thinking:

**Comment by clux** [comment]
Released the fix in 0.22.2. Thanks for the report and thanks once again @kitfre :clap:

**Comment by clux** [comment]
Most reflector examples have been updated, you should not need to wrap anything in `Arc` because `Reflector` and `Informer` implement `Clone` and maintain `Arc`s under the hood.

**Comment by milesgranger** [comment]
Most excellent, thank you so much! :tada:
